SSAFY-ALGO-STUDY-G3/Algorithm-Study

- 준수/BOJ_1012.py
- 준수/BOJ_16953.py
- 준수/BOJ_1743.py
> [BOJ] 1012. 유기농 배추 외 2

- 정환/[BOJ]1041.py
- 정환/[BOJ]12904.py
- 정환/[BOJ]15903.py
- 정환/[BOJ]9372.py
[BOJ] 15903. 카드 합체 놀이 / [BOJ] 1041. 주사위 / [BOJ] 9372. 상근이의 여행 / [BOJ] 12904. A와 B
> [BOJ] 15903 / [BOJ] 1041 / [BOJ] 9372 / [BOJ] 12904

- 경범/BOJ 6198
> Create BOJ 6198

- 경범/BOJ 2470 두 용액.py
> Create BOJ 2470 두 용액.py

- 경범/BOJ 29792 보스돌이.py
> Create BOJ 29792 보스돌이.py

- 재평/16928_뱀과 사다리 게임.py
> [BOJ] 16928. 뱀과 사다리 게임

- 지연김/pgs_12913.py
- 지연김/pgs_43165.py
> 231211_monday

- 지연김/pgs_81302.py
> [PGS] 81302 거리두기 확인하기

- 지연김/pgs_42577.py
> [PGS] 42577. 전화번호 목록

- 지연김/pgs_12978.py
> [PGS] 12978. 배달

- 지연김/pgs_176962.py
> [PGS] 176962. 과제진행하기

- 지연김/pgs_160585.py
> [PGS] 160585. 혼자서 하는 틱택토

- 지연김/pgs_148653.py
> [PGS] 148653. 마법의 엘리베이터

- 지연김/pgs_72411.py
> [PGS] 72411. 메뉴 리뉴얼

- 지연김/pgs_154540.py
> [PGS] 154540. 무인도 여행

- 지연김/240104/pgs_12981.py
> [PGS] 12981. 끝말잇기

- 지연김/240104/pgs_12981.js
> [PGS] 12981. 영어 끝말잇기

- 지연김/240107/pgs_77485.js
> [PGS] 77485. 행렬 테두리 회전하기

- 지연김/240110/pgs_43162.py
> [PGS] 43162. 네트워크

- 지연김/230112/pgs_43105.js
> [PGS] 43105. 정수 삼각형

- 지연김/230114/pgs_12927.js
야근지수 시간초과났는데요 일단 제출함
disclaimer : 문제 두개 다 우선순위큐로 풀려고 하는데 js로 도저히 어케하는지 모르겠고
class 만들고 별 난리 다했는데 일단 안됨;
오늘은 너무 시간을 많이 쏟아서 내일 다시해보겠습니다
> [PGS] 12927 야근지수

- 지연김/240120/pgs_178870.js
> [PGS] 178870 연속된 부분 수열의 합

- 지연김/230219/pgs_42586.js
> [PGS] 42586. 기능개발
